### ISSUE TITLE
Is this still valid? 

### ISSUE THREAD

**Issue by ramona-cristea** [dropbox/dropbox-api-content-hasher#7]
After checking Dropbox API v2 Java documentation, I could not find any `content_hash` field for FileMetaData. 
Please see https://dropbox.github.io/dropbox-sdk-java/api docs/v2.1.x/com/dropbox/core/v2/files/FileMetadata.html

Is this still valid, or the content hash was replaced with something else?
How one can check if a local file is the same as the version on server? By using the `rev` and `serverModified` properties?

Thank you in advance for you explanation!

**Comment by greg-db** [comment]
This is still valid. The documentation you're looking at is for the older v2.x of the Java SDK, which doesn't have `content_hash`. [The latest version](https://github.com/dropbox/dropbox-sdk-java/releases
) is v3.0.6, which does contain `content_hash`. You can find the documentation for that here:

https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/FileMetadata.html#contentHash

**Comment by ramona-cristea** [comment]
Thank you @greg-db for your fast reply! Maybe you could update also your official site? It still points to the old Java documentation v2.1.x.
